// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
struct Cube
{
    float3 pos;
    float4 color;
};
int width;
RWStructuredBuffer<Cube> cubes;
RWTexture2D<float4> Result;

[numthreads(16,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Cube cube = cubes[id.x*width + id.y];
    cube.color = Result[id.xy];
    cube.pos = float3(id.x,0,id.y);
    cubes[id.x*width + id.y] = cube;
}
